// ARTICLES
const header = document.querySelector('#header');
const search = document.querySelector('#search')
const main = document.querySelector('#main');
const categories = document.querySelector('.categoriesContainer');
const trending = document.querySelector('.trendingContainer');
const topRated = document.querySelector('#topRated');
const general = document.querySelector('.generalContainer');
const movieDetail = document.querySelector('#movieDetail');
const similarMovies = document.querySelector('#similarMovies');
const favorited = document.querySelector('#favorited');

// SECTIONS && CONTAINERS
const header_arrow = document.querySelector('.header_arrow');
const header_articule = document.querySelector('.header_articule');
const header_articule_sLeft = document.querySelector('.header_articule_sLeft');
const header_articule_sCenter = document.querySelector('.header_articule_sCenter');
const header_articule_sRight = document.querySelector('.header_articule_sRight');
const searchContainer_content = document.querySelector('.searchContainer_content');
const categories_titles = document.querySelector('.categories_titles');
const categories_sections = document.querySelector('#categories .categories_sections');
const categories_content = document.querySelector('.categories-content');
const movieContent = document.querySelector('#trending .movieContent');
const trendingContainer_movie_div = document.querySelector('.trendingContainer_movie_div');
const relatedContainer = document.querySelector('.relatedContainer');
const relatedContainerScrollContainer = document.querySelector('.relatedContainer-scrollContainer');
const movie_container = document.querySelector('.movie-container');
const movieDetail_categories = document.querySelector('.movieDetail_categories');
const similar_movieContent = document.querySelector('.similar-movieContent');
const TopRated_movieContent = document.querySelector('.TopRated-movieContent');
const movie_container_loading = document.querySelector('.movie-container--loading');
const trendingContainer_movie_div_loading = document.querySelector('.trendingContainer_movie_div--loading');
const similar_movieContent_loading = document.querySelector('.similar-movieContent--loading');
const categories_content_loading = document.querySelector('.categories-content--loading');
const favoritedContent = document.querySelector('#favoritedContainer');
const languageOptions = document.querySelector('#languageOptions');

// ELEMENTS
const header_arrow_button_back = document.querySelector('.header_arrow-button-back');
const header_arrow_button_reload = document.querySelector('.header_arrow-button-reload');
const header_arrow_span = document.querySelector('.header_arrow-span');
const header_articule_Sleft_title = document.querySelector('.header_articule_Sleft-title');
const header_articule_sLeft_text = document.querySelector('.header_articule_Sleft-text');
const header_articule_Sleft_title_categoryView = document.querySelector('.header_articule_Sleft-title--categoryView');
const header_articule_sRight_image = document.querySelector('.header_articule_sRight-image');
const iconSearch = document.querySelector('#iconSearch');
const inputsearch = document.querySelector('#inputsearch');
const iconMicrophone = document.querySelector('#iconMicrophone');
const categories_titles_h2 = document.querySelector('#categories_titles-h2');
const categories_content_h3 = document.querySelector('.categories-content-h3');
const categories_titles_span = document.querySelector('#categories_titles-span');
const trendingContainer_div_title = document.querySelector('.trendingContainer_div-title');
const trendingContainer_div_btn = document.querySelector('.trendingContainer_div-btn');
const movie_img = document.querySelector('.movie-img');
const categories_content_span = document.querySelector('.ategories-content-span');
const relatedContainer_title = document.querySelector('.relatedContainer-title');
const categories_titles_h2_detail = document.querySelector('.categories_titles-h2--detail');
const topRated_btn = document.querySelector('#topRated_btn');
const trending_btn = document.querySelector('#trending_btn');
const categories_titles_detail_title = document.querySelector('.categories_titles--detail-title');
const categories_titles_detail_span = document.querySelector(".categories_titles--detail-span");
const categories_titles_detail_description = document.querySelector(".categories_titles--detail-description");
const languageOptions_btn = document.querySelector(".languageOptions-btn");